---
baseURL: https://example.com
languageCode: en-us
title: Hugo Novela
pygmentsstyle: monokai
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
menu:
  main:
  - url: "/about/"
    name: About
    title: blog section
    weight: 1
    identifier: blog
