---
baseURL: https://example.com
languageCode: en-us
title: Rishabh Parekh's Diversity Archive
pygmentsstyle: monokai
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
menu:
  main:
  - url: "/contact/"
    name: Contact
    weight: 2
  - url: "/about/"
    name: About
    title: About Us
    weight: 1
